# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef1001de6b8ce5ad4967a5b670ea8fabf01b6ae2257d742e42754b996ac18ce06925cb8e0ac80a99daba9f4b7681bc644618d617af4566f1fa4af786c0a10c01

test:
  secret_key_base: 6b4bb7ddce1fbc001d674829f9b6592c090689805e4409d9c1e71ddc732a1bc8ab45cad7b1a4c00360d5e13c5b56ad5a086422ea48031c77767600a9aa5078c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
